package com.clo.closs.domain.model

import com.clo.closs.data.local.entities.ProductEntity

data class Product(
    val enpreventa: String = "",
    val vtaSolofac: Int = 0,
    val grupo: String = "",
    val nombre: String = "",
    val existencia: Int = 0,
    val marca: String = "",
    val createdAt: String = "",
    val productImage: String = "",
    val comprometido: Int = 0,
    val subgrupo: String = "",
    val vtaSolone: Int = 0,
    val vtaMax: Int = 0,
    val discont: Int = 0,
    val vtaMinenx: Int = 0,
    val codigo: String = "",
    val vtaMin: Int = 0,
    val dctotope: Double = 0.0,
    val precio1: Double = 0.0,
    val precio2: Double = 0.0,
    val precio3: Double = 0.0,
    val precio4: Double = 0.0,
    val precio5: Double = 0.0,
    val precio6: Double = 0.0,
    val precio7: Double = 0.0,
    val unidad: String = "",
    val deletedAt: String? = "",
    val fechamodifi: String = "",
    val referencia: String = ""
) {
    fun toDataBase() = ProductEntity(
        enpreventa = enpreventa,
        vtaSolofac = vtaSolofac,
        grupo = grupo,
        nombre = nombre,
        existencia = existencia,
        marca = marca,
        createdAt = createdAt,
        productImage = productImage,
        comprometido = comprometido,
        subgrupo = subgrupo,
        vtaSolone = vtaSolone,
        vtaMax = vtaMax,
        discont = discont,
        vtaMinenx = vtaMinenx,
        codigo = codigo,
        vtaMin = vtaMin,
        dctotope = dctotope,
        precio1 = precio1,
        precio2 = precio2,
        precio3 = precio3,
        precio4 = precio4,
        precio5 = precio5,
        precio6 = precio6,
        precio7 = precio7,
        unidad = unidad,
        deletedAt = deletedAt,
        fechamodifi = fechamodifi,
        referencia = referencia,
    )
}
